//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopChart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BillingData
    {
        [Display(Name = "Your Email")]
        [Required(ErrorMessage = "Required Field")]
        [DataType(DataType.EmailAddress, ErrorMessage = "This must be a valid email address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Required Field")]
        [Range(0, 100, ErrorMessage = "This must not be greater than 100")]
        public int ID { get; set; }

        [Required(ErrorMessage = "Required Field")]
        public string Contact { get; set; }

        [Required(ErrorMessage = "Required Field")]
        public string BillingAdress { get; set; }

         [Required(ErrorMessage = "Required Field")]
         [StringLength(10, ErrorMessage = "Classification Code Length must not be greater than 10")]
        public string ClassificationCode { get; set; }
    
        public virtual RegisterCustomer RegisterCustomer { get; set; }
    }
}
