//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopChart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Contact
    {
        [Display(Name = "Your Email")]
        [Required(ErrorMessage = "Required Field")]
        [DataType(DataType.EmailAddress, ErrorMessage = "This must be a valid email address")]
        public string Email { get; set; }
        [Display(Name = "Your Name")]
        [Required(ErrorMessage = "Required Field")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Required Field")]
        [Display(Name = "Your Subject")]
        public string Subject { get; set; }

        [Required(ErrorMessage = "Required Field")]
        [Display(Name = "Your Message for us")]
        ////[StringLength(50, ErrorMessage = "Message Length must not be greater than 5")]
        //[Range(0, 100, ErrorMessage = "This must not be greater than 100")]
        public string Message { get; set; }

        [Required(ErrorMessage = "The ID field is required")]
        [Range(0, 100, ErrorMessage = "This must not be greater than 100")]
        public int ID { get; set; }
    }
}
