//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo
    {
        public string ProductID { get; set; }
        public Nullable<int> Price { get; set; }
        public string Category { get; set; }
        public string Color { get; set; }
        public string Brand { get; set; }
        public string Entery_Date { get; set; }
        public string ChooseImage { get; set; }
    }
}
