//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterCustomer
    {
        public RegisterCustomer()
        {
            this.BillingDatas = new HashSet<BillingData>();
            this.PurchasedDatas = new HashSet<PurchasedData>();
        }
    
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string Password { get; set; }
        public string DOB { get; set; }
    
        public virtual ICollection<BillingData> BillingDatas { get; set; }
        public virtual ICollection<PurchasedData> PurchasedDatas { get; set; }
    }
}
