//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopChart.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopCartDbEntities18 : DbContext
    {
        public ShopCartDbEntities18()
            : base("name=ShopCartDbEntities18")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BillingData> BillingDatas { get; set; }
        public DbSet<Cart> Carts { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<ProductInfo> ProductInfoes { get; set; }
        public DbSet<PurchasedData> PurchasedDatas { get; set; }
        public DbSet<RegisterAdmin> RegisterAdmins { get; set; }
        public DbSet<RegisterCustomer> RegisterCustomers { get; set; }
    }
}
